version: 1

project_id: olist-meng-hai
send_anonymous_usage_stats: false

default_environment: prod

environments:
  - name: prod

plugins:
  extractors:
    - name: tap-csv
      namespace: tap_csv
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
      executable: tap-csv
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: files
          kind: array
      config:
        files:
          - entity: orders
            path: ../../../../data/olist_orders_dataset.csv
            keys:
              - order_id
          - entity: order_items
            path: ../../../../data/olist_order_items_dataset.csv
            keys:
              - order_id
              - order_item_id
          - entity: order_payments
            path: ../../../../data/olist_order_payments_dataset.csv
            keys:
              - order_id
              - payment_sequential
          - entity: order_reviews
            path: ../../../../data/olist_order_reviews_dataset.csv
            keys:
              - review_id
          - entity: customers
            path: ../../../../data/olist_customers_dataset.csv
            keys:
              - customer_id
          - entity: products
            path: ../../../../data/olist_products_dataset.csv
            keys:
              - product_id
          - entity: sellers
            path: ../../../../data/olist_sellers_dataset.csv
            keys:
              - seller_id
          - entity: geolocation
            path: ../../../../data/olist_geolocation_dataset.csv
            keys:
              - geolocation_zip_code_prefix

  loaders:
    - name: target-gcs
      variant: ticketswap
      pip_url: git+https://github.com/TicketSwap/target-gcs.git
      executable: target-gcs
      config:
        bucket: olist-meng-hai-landing
        prefix: raw/

jobs:
  - name: olist-el
    tasks:
      - tap-csv target-bigquery
